version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "13306:3306"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app_name
    ports:
      - "3000:3000"
    # links:
    # - db
    # - redis
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
  redis:
    image: redis:5.0.3
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    command: redis-server --appendonly yes
volumes:
  db-volume:
  redis:
    driver: local
  bundle:
    driver: local
